package visao;

import java.awt.Image;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author yosh
 */
public class TelaUno extends javax.swing.JFrame {

    /**
     * Creates new form TelaUno
     */
    private DefaultListModel listaEsquerdo, listaDireito;
    private Baralho baralho;
    private Jogador jogador, computador;
    private Mesa mesa;
    
    public TelaUno() throws IOException {
        initComponents();
        
        //Inicialização das classes que tornam possível a adição na lista
        listCartasEsquerdo.setModel(new DefaultListModel());
        listCartasDireito.setModel(new DefaultListModel());
        listaDireito = (DefaultListModel) listCartasDireito.getModel();
        listaEsquerdo = (DefaultListModel) listCartasEsquerdo.getModel();
        //Inicializando variáveis
        baralho = new Baralho();
        mesa = new Mesa(baralho);
        jogador = new Jogador(JOptionPane.showInputDialog("Digite seu nome"));
        lblNomeJogador.setText(jogador.getNome());
        computador = new Jogador("Computador");
        //Criando novo jogo
        mesa.iniciarNovoJogo(jogador, computador);
        //Preenchendo listas
        for(Carta x : jogador.getMao()){
            listaDireito.addElement(exibirCarta(x));
        }
        for(int i = 1; i <= computador.getMao().size(); i++){
            listaEsquerdo.addElement("Carta " + i);
        }
        
        //Carregando as imagens
        ImageIcon iconeBaralho = new ImageIcon(getClass().getResource("/imagens/verso.png"));
              
        imagemBaralho.setIcon( ajustarImagem(iconeBaralho));
        imagemMonte.setIcon( ajustarImagem(mesa.verTopoMonte().getImagem()));
        imagemBaralho.setText("");
        imagemMonte.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spCartas = new javax.swing.JScrollPane();
        listCartasEsquerdo = new javax.swing.JList<>();
        lblCartas = new javax.swing.JLabel();
        btnJogarCartaEsquerdo = new javax.swing.JButton();
        btnUnoEsquerdo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        spCartas1 = new javax.swing.JScrollPane();
        listCartasDireito = new javax.swing.JList<>();
        lblNomeJogador = new javax.swing.JLabel();
        btnJogarCartaDireito = new javax.swing.JButton();
        btnUnoDireito = new javax.swing.JButton();
        imagemMonte = new javax.swing.JLabel();
        imagemBaralho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listCartasEsquerdo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCartasEsquerdo.setEnabled(false);
        listCartasEsquerdo.setFocusable(false);
        spCartas.setViewportView(listCartasEsquerdo);

        lblCartas.setText("Computador");

        btnJogarCartaEsquerdo.setText("Jogar Carta");
        btnJogarCartaEsquerdo.setEnabled(false);

        btnUnoEsquerdo.setText("UNO!");
        btnUnoEsquerdo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblCartas)
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(spCartas)
            .addComponent(btnJogarCartaEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUnoEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCartas)
                .addGap(6, 6, 6)
                .addComponent(spCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJogarCartaEsquerdo)
                .addGap(43, 43, 43)
                .addComponent(btnUnoEsquerdo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listCartasDireito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spCartas1.setViewportView(listCartasDireito);

        lblNomeJogador.setText("Nome Jogador");

        btnJogarCartaDireito.setText("Jogar Carta");
        btnJogarCartaDireito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarCartaDireitoActionPerformed(evt);
            }
        });

        btnUnoDireito.setText("UNO!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblNomeJogador)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(spCartas1)
            .addComponent(btnJogarCartaDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUnoDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblNomeJogador)
                .addGap(6, 6, 6)
                .addComponent(spCartas1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJogarCartaDireito)
                .addGap(43, 43, 43)
                .addComponent(btnUnoDireito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagemMonte.setText("imagemMonte");
        imagemMonte.setMaximumSize(new java.awt.Dimension(80, 130));
        imagemMonte.setMinimumSize(new java.awt.Dimension(80, 130));

        imagemBaralho.setText("imagemBaralho");
        imagemBaralho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagemBaralhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemMonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemBaralho))
                .addGap(74, 74, 74)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(imagemMonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(imagemBaralho))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarCartaDireitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarCartaDireitoActionPerformed
        /*
        *   Verificar carta selecionada
        *   Verificar se ela pode ser jogada
        *   Jogar a carta
        *   Tirar a carta da lista/mão do jogador
        */
        //---- Joga
        mesa.colocaNoTopoMonte(jogador.jogarCarta(listCartasDireito.getSelectedIndex()));
        //----
        //-----Remove a carta da lista e atualiza a imagem do monte
        listaDireito.remove( listCartasDireito.getSelectedIndex());
        imagemMonte.setIcon( ajustarImagem(mesa.verTopoMonte().getImagem()));
        //-----
    }//GEN-LAST:event_btnJogarCartaDireitoActionPerformed

    private void imagemBaralhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagemBaralhoMouseClicked
        jogador.compraCarta( baralho.darCarta());
        listaDireito.addElement( exibirCarta(jogador.getMao().get(jogador.getMao().size()-1)));
    }//GEN-LAST:event_imagemBaralhoMouseClicked

    private String exibirCarta(Carta x){	//Função que exibe as informaçães da carta
        if(x instanceof CartaNumero){
            CartaNumero k = (CartaNumero)x;
            return k.getNumero() + " " + k.getCor();
        }else
            if(x instanceof CartaSimbolo){
                CartaSimbolo k = (CartaSimbolo)x;
                return k.getSimbolo() + " " + k.getCor();
            }else{
                    CartaEspecial k = (CartaEspecial)x;
                    return k.getEspecial();
		 }
    }
    
    private ImageIcon ajustarImagem(ImageIcon imagem){
        imagem.setImage(imagem.getImage().getScaledInstance(93, 139, Image.SCALE_SMOOTH));
        return imagem;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogarCartaDireito;
    private javax.swing.JButton btnJogarCartaEsquerdo;
    private javax.swing.JButton btnUnoDireito;
    private javax.swing.JButton btnUnoEsquerdo;
    private javax.swing.JLabel imagemBaralho;
    private javax.swing.JLabel imagemMonte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCartas;
    private javax.swing.JLabel lblNomeJogador;
    private javax.swing.JList<String> listCartasDireito;
    private javax.swing.JList<String> listCartasEsquerdo;
    private javax.swing.JScrollPane spCartas;
    private javax.swing.JScrollPane spCartas1;
    // End of variables declaration//GEN-END:variables
}
